In [1]:
import numpy as np

# Q1. Is there any difference in the data type of variables `list_` and `array_list`? 
# If there is, then write code to print the data types of both the variables.

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Check and print data types
if list_:
    print(f"Data type of list_: {type(list_[0])}")
if array_list.size > 0:
    print(f"Data type of array_list: {array_list.dtype}")

# Q2. Write code to print the data type of each and every element of both the variables `list_` and `array_list`.

# Print data types of each element
if list_:
    print(f"Data types of elements in list_: {[type(item) for item in list_]}")
if array_list.size > 0:
    print(f"Data types of elements in array_list: {array_list.dtype}")

# Q3. Considering the following changes in the variable `array_list`:
# array_list = np.array(object=list_, dtype=int)
# Will there be any difference in the data type of the elements present in both the variables, `list_` and `array_list`? 
# If so, then print the data types of each and every element present in both the variables, `list_` and `array_list`.

# Check and print data types after dtype conversion
array_list = np.array(object=list_, dtype=int)
if list_:
    print(f"Data types of elements in list_ (before): {[type(item) for item in list_]}")
if array_list.size > 0:
    print(f"Data types of elements in array_list (after): {array_list.dtype}")

# Q4. Write code to find the following characteristics of variable, `num_array`:
# (i) shape
# (ii) size

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
print(f"Shape of num_array: {num_array.shape}")

# (ii) Size
print(f"Size of num_array: {num_array.size}")

# Q5. Write code to create a numpy array of a 3x3 matrix containing zeros only, using a numpy array creation function.

zeros_array = np.zeros((3, 3))
print("3x3 matrix containing zeros:\n", zeros_array)

# Q6. Create an identity matrix of shape (5, 5) using numpy functions?

identity_matrix = np.identity(5)
print("Identity matrix of shape (5, 5):\n", identity_matrix)


Data type of list_: <class 'str'>
Data type of array_list: <U1
Data types of elements in list_: [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types of elements in array_list: <U1
Data types of elements in list_ (before): [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types of elements in array_list (after): int32
Shape of num_array: (2, 3)
Size of num_array: 6
3x3 matrix containing zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity matrix of shape (5, 5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [2]:
 print(f"Data type of array_list: {array_list.dtype}")

Data type of array_list: int32
